name: Build and Test C++ Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # 检出您的代码

    - name: Build and Test with Docker
      run: |
        docker run -v ${{ github.workspace }}:/app maxxing/compiler-dev /bin/bash -c "cd /app && make"
